apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: fastapi-ci-
  namespace: argo
spec:
  entrypoint: ci-pipeline
  serviceAccountName: argo-sa

  templates:

  - name: ci-pipeline
    dag:
      tasks:

      - name: build-image
        template: kaniko-build

      - name: sync-argocd
        template: argocd-sync
        dependencies: [build-image]

  - name: kaniko-build
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/zi-fei-yu-2020/fastapi-argo-demo.git"
        - "--destination=<your-dockerhub-username>/fastapi-demo:latest"
        - "--skip-tls-verify"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    volumes:
      - name: docker-config
        secret:
          secretName: dockerhub-secret

  - name: argocd-sync
    container:
      image: argoproj/argocd-cli:v2.6.7
      command: [sh, -c]
      args:
        - |
          argocd login argo-server.argo.svc.cluster.local:443 \
          --username admin \
          --password $ARGOCD_PASSWORD \
          --insecure
          argocd app sync fastapi-demo
      env:
        - name: ARGOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-secret
              key: password
