apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zi-fei-yu-2020/fastapi-argo-demo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true        # 删除 Git 上不存在的资源
      selfHeal: true     # 自动修复 drift
